japan_prefectures = {
    "major": ["Osaka", "Kyoto", "Aichi", "Tokyo", "Kanagawa", "Hokkaido"],
    "minor": ["Aomori", "Iwate", "Miyagi", "Akita", "Yamagata", "Fukushima", 
    "Ibaraki", "Tochigi", "Gunma", "Saitama", "Chiba", "Niigata", "Toyama", "Ishikawa", "Fukui", "Yamanashi", "Nagano", "Gifu", 
    "Shizuoka", "Mie", "Shiga", "Hyogo", "Nara", "Wakayama", "Tottori", "Shimane", "Okayama", "Hiroshima", "Yamaguchi", "Tokushima", "Kagawa", "Ehime", "Kochi", "Fukuoka", "Saga", "Nagasaki", "Kumamoto", "Oita", "Miyazaki", "Kagoshima", "Okinawa"]
}

japan_prefectures_cities = {
  "Hokkaido": [
    "Sapporo",
    "Hakodate",
    "Asahikawa",
    "Otaru",
    "Muroran",
    "Kitami",
    "Kushiro",
    "Obihiro",
    "Chitose",
    "Tomakomai",
    "Bihoro",
    "Suttsu",
    "Nakashibetsu",
    "Yubari",
    "Engaru",
    "Shiraoi",
    "Iwamizawa",
    "Nakafurano",
    "Tsubetsu",
    "Rishiri",
  ],
  "Aomori": [
    "Aomori",
    "Hachinohe",
    "Hirosaki",
    "Towada",
    "Mutsu",
    "Misawa",
    "Goshogawara",
    "Shichinohe",
    "Kuroishi",
    "Oirase",
  ],
  "Iwate": [
    "Morioka",
    "Ichinoseki",
    "Kamaishi",
    "Oshu",
    "Hanamaki",
    "Miyako",
    "Tono",
    "Ninohe",
    "Shizukuishi",
    "Yamada",
  ],
  "Miyagi": [
    "Sendai",
    "Ishinomaki",
    "Shiogama",
    "Tome",
    "Kurihara",
    "Shiroishi",
    "Zao",
    "Natori",
    "Tagajo",
    "Sakata",
  ],
  "Akita": [
    "Akita",
    "Yokote",
    "Noshiro",
    "Kazuno",
    "Daisen",
    "Inaba",
    "Semboku",
    "Mitane",
    "Takanosu",
    "Odate",
  ],
  "Yamagata": [
    "Yamagata",
    "Yonezawa",
    "Tendo",
    "Zao",
    "Kaminoyama",
    "Sagae",
    "Murayama",
    "Yamagata",
    "Shinjo",
    "Nanyo",
  ],
  "Fukushima": [
    "Fukushima",
    "Koriyama",
    "Aizuwakamatsu",
    "Shirakawa",
    "Kawamata",
    "Ishikawa",
    "Soma",
    "Minamisoma",
    "Nihonmatsu",
    "Tadami",
  ],
  "Ibaraki": [
    "Mito",
    "Tsukuba",
    "Hitachi",
    "Kashima",
    "Sakuragawa",
    "Naka",
    "Koga",
    "Hitachiota",
    "Tsuchiura",
    "Oarai",
  ],
  "Tochigi": [
    "Utsunomiya",
    "Ashikaga",
    "Nikko",
    "Tama",
    "Tatebayashi",
    "Sano",
    "Nakagawa",
    "Kanuma",
    "Moka",
    "Kuroiso",
  ],
  "Gunma": [
    "Maebashi",
    "Takasaki",
    "Isesaki",
    "Kiryu",
    "Tatebayashi",
    "Numata",
    "Ota",
    "Shibukawa",
    "Minakami",
    "Fujioka",
  ],
  "Saitama": [
    "Saitama",
    "Kawaguchi",
    "Koshigaya",
    "Omiya",
    "Kasukabe",
    "Urawa",
    "Kawagoe",
    "Higashimatsuyama",
    "Soka",
    "Ageo",
  ],
  "Chiba": [
    "Chiba",
    "Narita",
    "Matsudo",
    "Kashiwa",
    "Funabashi",
    "Ichikawa",
    "Sakura",
    "Tateyama",
    "Urayasu",
    "Kamagaya",
  ],
  "Tokyo": [
    "Shinjuku",
    "Shibuya",
    "Chiyoda",
    "Setagaya",
    "Ikebukuro",
    "Ota",
    "Toshima",
    "Koto",
    "Bunkyo",
    "Edogawa",
    "Sumida",
    "Chuo",
    "Arakawa",
    "Adachi",
    "Nakano",
    "Suginami",
    "Meguro",
    "Kita",
    "Taito",
  ],
  "Kanagawa": [
    "Yokohama",
    "Kawasaki",
    "Sagamihara",
    "Odawara",
    "Yokosuka",
    "Fujisawa",
    "Chigasaki",
    "Zushi",
    "Atsugi",
    "Kamakura",
    "Minamiashigara",
    "Hayama",
    "Totsuka",
    "Hadano",
    "Ebina",
    "Isehara",
    "Miura",
    "Sakae",
    "Kawasaki",
    "Tama",
  ],
  "Niigata": [
    "Niigata",
    "Joetsu",
    "Nagaoka",
    "Tsubame",
    "Sanjo",
    "Murakami",
    "Sado",
    "Niitsu",
    "Agano",
    "Kamo",
  ],
  "Toyama": [
    "Toyama",
    "Takaoka",
    "Uozu",
    "Fushiki",
    "Imizu",
    "Nanto",
    "Tonami",
    "Kurobe",
    "Shinminato",
    "Kamiichi",
  ],
  "Ishikawa": [
    "Kanazawa",
    "Wajima",
    "Tsubata",
    "Nonoichi",
    "Suematsu",
    "Shika",
    "Hakusan",
    "Kaga",
    "Takaoka",
    "Anamizu",
  ],
  "Fukui": [
    "Fukui",
    "Sakai",
    "Echizen",
    "Takahama",
    "Ono",
    "Katsuyama",
    "Obama",
    "Sabae",
    "Takefu",
    "Awano",
  ],
  "Yamanashi": [
    "Kofu",
    "Fujiyoshida",
    "Minami Alps",
    "Katsunuma",
    "Tomi",
    "Yamanashi",
    "Fujikawaguchiko",
    "Nirasaki",
    "Fujinomiya",
    "Nanbu",
  ],
  "Nagano": [
    "Nagano",
    "Matsumoto",
    "Suwa",
    "Shiojiri",
    "Iida",
    "Karuizawa",
    "Ueda",
    "Nagano",
    "Okaya",
    "Azumino",
  ],
  "Gifu": [
    "Gifu",
    "Takayama",
    "Ogaki",
    "Kakamigahara",
    "Ichinomiya",
    "Seki",
    "Gero",
    "Tarui",
    "Toki",
    "Minokamo",
  ],
  "Shizuoka": [
    "Shizuoka",
    "Hamamatsu",
    "Numazu",
    "Fujinomiya",
    "Kakegawa",
    "Mishima",
    "Ito",
    "Fujieda",
    "Iwata",
    "Toyohashi",
  ],
 "Aichi": [
    "Nagoya",
    "Toyota",
    "Okazaki",
    "Ichinomiya",
    "Nagakute",
    "Toyokawa",
    "Seto",
    "Aichi",
    "Kariya",
    "Tahara",
    "Anjo",
    "Gamou",
    "Nishio",
    "Inazawa",
    "Togo",
    "Shinshiro",
    "Tojo",
    "Aisai",
    "Mikawa",
    "Komaki",
  ],
  "Mie": [
    "Tsu",
    "Ise",
    "Yokkaichi",
    "Kameyama",
    "Iga",
    "Kashihara",
    "Shima",
    "Owase",
    "Kuwana",
    "Taki",
  ],
  "Shiga": [
    "Otsu",
    "Kusatsu",
    "Hikone",
    "Omihachiman",
    "Koka",
    "Tachikawa",
    "Minami-Kyoto",
    "Inuyama",
    "Yasu",
    "Nagahama",
  ],
  "Kyoto": [
    "Kyoto",
    "Uji",
    "Kameoka",
    "Maizuru",
    "Fushimi",
    "Nagaokakyo",
    "Kizugawa",
    "Kyotanabe",
    "Seika",
    "Sakyo",
    "Fushimi",
    "Joyo",
    "Wazuka",
    "Kizugawa",
    "Nantan",
    "Kyotanabe",
    "Oyamazaki",
    "Mukaijima",
    "Ibaraki",
  ],
  "Osaka": [
    "Osaka",
    "Sakai",
    "Takaishi",
    "Hirakata",
    "Toyonaka",
    "Takatsuki",
    "Ibaraki",
    "Suita",
    "Daito",
    "Suminoe",
    "Ikeda",
    "Amagasaki",
    "Settsu",
    "Kadoma",
    "Kishiwada",
    "Kawachinagano",
    "Osakasayama",
    "Minoh",
    "Sumoto",
    "Tondabayashi",
  ],
  "Hyogo": [
    "Kobe",
    "Himeji",
    "Amagasaki",
    "Takarazuka",
    "Nishinomiya",
    "Kozu",
    "Sanda",
    "Toyooka",
    "Tatsuno",
    "Minamiawaji",
  ],
  "Nara": [
    "Nara",
    "Yamatokoriyama",
    "Sakurai",
    "Tenri",
    "Kashihara",
    "Ikoma",
    "Koryo",
    "Heguri",
    "Gose",
    "Sango",
  ],
  "Wakayama": [
    "Wakayama",
    "Shingu",
    "Kainan",
    "Tanabe",
    "Arida",
    "Gobo",
    "Kihoku",
    "Wakayama",
    "Kozagawa",
    "Yura",
  ],
  "Tottori": [
    "Tottori",
    "Kurayoshi",
    "Yonago",
    "Sakaiminato",
    "Kurayoshi",
    "Tatsuno",
    "Hojyo",
    "Koyama",
    "Bunroku",
    "Kamo",
  ],
  "Shimane": [
    "Matsue",
    "Izumo",
    "Unnan",
    "Hamada",
    "Oki",
    "Masuda",
    "Kara",
    "Mihonoseki",
    "Yatsuka",
    "Taki",
  ],
  "Okayama": [
    "Okayama",
    "Kurashiki",
    "Tamano",
    "Sanyo",
    "Fukuda",
    "Kibichuo",
    "Mimasaka",
    "Osafune",
    "Seto",
    "Bizen",
  ],
  "Hiroshima": [
    "Hiroshima",
    "Kure",
    "Fukuyama",
    "Onomichi",
    "Takehara",
    "Miyoshi",
    "Mihara",
    "Akiota",
    "Saeki",
    "Hatsukaichi",
  ],
  "Yamaguchi": [
    "Yamaguchi",
    "Shimonoseki",
    "Ube",
    "Shuho",
    "Iwakuni",
    "Hofu",
    "Yoshiki",
    "Sanyo",
    "Tabuse",
    "Kudamatsu",
  ],
  "Tokushima": [
    "Tokushima",
    "Anan",
    "Mugi",
    "Komatsu",
    "Tatsuno",
    "Takamatsu",
    "Zentsuji",
    "Awa",
    "Toba",
    "Nio",
  ],
  "Kagawa": [
    "Takamatsu",
    "Marugame",
    "Tobe",
    "Sakaide",
    "Kanonji",
    "Mitoyo",
    "Sanuki",
    "Tamaoka",
    "Zentsuji",
    "Kotohira",
  ],
  "Ehime": [
    "Matsuyama",
    "Imabari",
    "Niihama",
    "Uwajima",
    "Shikokuchuo",
    "Ozu",
    "Saijyo",
    "Tobe",
    "Yawatahama",
    "Matsuno",
  ],
  "Kochi": [
    "Kochi",
    "Nankoku",
    "Ooka",
    "Niyodogawa",
    "Kochi",
    "Aki",
    "Sukumo",
    "Konan",
    "Mihara",
    "Tosa",
  ],
  "Fukuoka": [
    "Fukuoka",
    "Kitakyushu",
    "Kurume",
    "Nagasaki",
    "Koga",
    "Onojo",
    "Chikuzen",
    "Dazaifu",
    "Yame",
    "Yanagawa",
  ],
  "Saga": [
    "Saga",
    "Karatsu",
    "Imari",
    "Tosu",
    "Shiroishi",
    "Kawasaki",
    "Kudoyama",
    "Saga",
    "Ureshino",
    "Takeo",
  ],
  "Nagasaki": [
    "Nagasaki",
    "Sasebo",
    "Isahaya",
    "Taku",
    "Unzen",
    "Shimabara",
    "Omura",
    "Nagayo",
    "Goto",
    "Yukawa",
  ],
  "Kumamoto": [
    "Kumamoto",
    "Yatsushiro",
    "Amakusa",
    "Kikuchi",
    "Arao",
    "Hitoyoshi",
    "Uto",
    "Takamori",
    "Kosa",
    "Kamimashiki",
  ],
  "Oita": [
    "Oita",
    "Beppu",
    "Nakatsu",
    "Usa",
    "Saiki",
    "Hita",
    "Kokonoe",
    "Taketa",
    "Kunisaki",
    "Bungotakada",
  ],
  "Miyazaki": [
    "Miyazaki",
    "Nichinan",
    "Kobayashi",
    "Nobeoka",
    "Saito",
    "Kirishima",
    "Hyuga",
    "Mimata",
    "Ebino",
    "Takanabe",
  ],
  "Kagoshima": [
    "Kagoshima",
    "Kanoya",
    "Izumi",
    "Satsumasendai",
    "Makurazaki",
    "Koshikijima",
    "Kirishima",
    "Amami",
    "Kagoshima",
    "Tarumizu",
  ],
  "Okinawa": [
    "Naha",
    "Okinawa",
    "Nago",
    "Kadena",
    "Uruma",
    "Itoman",
    "Motobu",
    "Onna",
    "Nanjo",
    "Ginoza",
  ]
}

prefecture_mapping = {
  "北海道": "Hokkaido",
  "青森県": "Aomori",
  "岩手県": "Iwate",
  "宮城県": "Miyagi",
  "秋田県": "Akita",
  "山形県": "Yamagata",
  "福島県": "Fukushima",
  "茨城県": "Ibaraki",
  "栃木県": "Tochigi",
  "群馬県": "Gunma",
  "埼玉県": "Saitama",
  "千葉県": "Chiba",
  "東京都": "Tokyo",
  "神奈川県": "Kanagawa",
  "新潟県": "Niigata",
  "富山県": "Toyama",
  "石川県": "Ishikawa",
  "福井県": "Fukui",
  "山梨県": "Yamanashi",
  "長野県": "Nagano",
  "岐阜県": "Gifu",
  "静岡県": "Shizuoka",
  "愛知県": "Aichi",
  "三重県": "Mie",
  "滋賀県": "Shiga",
  "京都府": "Kyoto",
  "大阪府": "Osaka",
  "兵庫県": "Hyogo",
  "奈良県": "Nara",
  "和歌山県": "Wakayama",
  "鳥取県": "Tottori",
  "島根県": "Shimane",
  "岡山県": "Okayama",
  "広島県": "Hiroshima",
  "山口県": "Yamaguchi",
  "徳島県": "Tokushima",
  "香川県": "Kagawa",
  "愛媛県": "Ehime",
  "高知県": "Kochi",
  "福岡県": "Fukuoka",
  "佐賀県": "Saga",
  "長崎県": "Nagasaki",
  "熊本県": "Kumamoto",
  "大分県": "Oita",
  "宮崎県": "Miyazaki",
  "鹿児島県": "Kagoshima",
  "沖縄県": "Okinawa"
}

city_mapping = {
  "Hokkaido": {
    "Sapporo": "札幌",
    "Hakodate": "函館",
    "Asahikawa": "旭川",
    "Otaru": "小樽",
    "Muroran": "室蘭",
    "Kitami": "北見",
    "Kushiro": "釧路",
    "Obihiro": "帯広",
    "Chitose": "千歳",
    "Tomakomai": "苫小牧",
    "Bihoro": "美幌",
    "Suttsu": "寿都",
    "Nakashibetsu": "中標津",
    "Yubari": "夕張",
    "Engaru": "遠軽",
    "Shiraoi": "白老",
    "Iwamizawa": "岩見沢",
    "Nakafurano": "中富良野",
    "Tsubetsu": "津別",
    "Rishiri": "利尻"
  },
  "Aomori": {
    "Aomori": "青森",
    "Hachinohe": "八戸",
    "Hirosaki": "弘前",
    "Towada": "十和田",
    "Mutsu": "むつ",
    "Misawa": "三沢",
    "Goshogawara": "五所川原",
    "Shichinohe": "七戸",
    "Kuroishi": "黒石",
    "Oirase": "おいらせ"
  },
  "Iwate": {
    "Morioka": "盛岡",
    "Ichinoseki": "一ノ関",
    "Kamaishi": "釜石",
    "Oshu": "大船渡",
    "Hanamaki": "花巻",
    "Miyako": "宮古",
    "Tono": "遠野",
    "Ninohe": "二戸",
    "Shizukuishi": "雫石",
    "Yamada": "山田"
  },
  "Miyagi": {
    "Sendai": "仙台",
    "Ishinomaki": "石巻",
    "Shiogama": "塩竈",
    "Tome": "登米",
    "Kurihara": "栗原",
    "Shiroishi": "白石",
    "Zao": "蔵王",
    "Natori": "名取",
    "Tagajo": "多賀城",
    "Sakata": "酒田"
  },
  "Akita": {
    "Akita": "秋田",
    "Yokote": "横手",
    "Noshiro": "能代",
    "Kazuno": "鹿角",
    "Daisen": "大仙",
    "Inaba": "稲葉",
    "Semboku": "仙北",
    "Mitane": "美郷",
    "Takanosu": "高野",
    "Odate": "大館"
  },
  "Yamagata": {
    "Yamagata": "山形",
    "Yonezawa": "米沢",
    "Tendo": "天童",
    "Zao": "蔵王",
    "Kaminoyama": "上山",
    "Sagae": "寒河江",
    "Murayama": "村山",
    "Shinjo": "新庄",
    "Nanyo": "南陽"
  },
  "Fukushima": {
    "Fukushima": "福島",
    "Koriyama": "郡山",
    "Aizuwakamatsu": "会津若松",
    "Shirakawa": "白河",
    "Kawamata": "川俣",
    "Ishikawa": "石川",
    "Soma": "相馬",
    "Minamisoma": "南相馬",
    "Nihonmatsu": "二本松",
    "Tadami": "只見"
  },
  "Ibaraki": {
    "Mito": "水戸",
    "Tsukuba": "つくば",
    "Hitachi": "日立",
    "Kashima": "鹿島",
    "Sakuragawa": "桜川",
    "Naka": "那珂",
    "Koga": "古河",
    "Hitachiota": "日立おおた",
    "Tsuchiura": "土浦",
    "Oarai": "大洗"
  },
  "Tochigi": {
    "Utsunomiya": "宇都宮",
    "Ashikaga": "足利",
    "Nikko": "日光",
    "Tama": "多摩",
    "Tatebayashi": "館林",
    "Sano": "佐野",
    "Nakagawa": "那賀川",
    "Kanuma": "鹿沼",
    "Moka": "真岡",
    "Kuroiso": "黒磯"
  },
  "Gunma": {
    "Maebashi": "前橋",
    "Takasaki": "高崎",
    "Isesaki": "伊勢崎",
    "Kiryu": "桐生",
    "Tatebayashi": "館林",
    "Numata": "沼田",
    "Ota": "太田",
    "Shibukawa": "渋川",
    "Minakami": "水上",
    "Fujioka": "藤岡"
  },
  "Saitama": {
    "Saitama": "さいたま",
    "Kawaguchi": "川口",
    "Koshigaya": "越谷",
    "Omiya": "大宮",
    "Kasukabe": "春日部",
    "Urawa": "浦和",
    "Kawagoe": "川越",
    "Higashimatsuyama": "東松山",
    "Soka": "草加",
    "Ageo": "上尾"
  },
  "Chiba": {
    "Chiba": "千葉",
    "Narita": "成田",
    "Matsudo": "松戸",
    "Kashiwa": "柏",
    "Funabashi": "船橋",
    "Ichikawa": "市川",
    "Sakura": "佐倉",
    "Tateyama": "館山",
    "Urayasu": "浦安",
    "Kamagaya": "鎌ケ谷"
  },

  "Tokyo": {
    "Shinjuku": "新宿",
    "Shibuya": "渋谷",
    "Chiyoda": "千代田",
    "Setagaya": "世田谷",
    "Ikebukuro": "池袋",
    "Ota": "大田",
    "Toshima": "豊島",
    "Koto": "江東",
    "Bunkyo": "文京",
    "Edogawa": "江戸川",
    "Sumida": "墨田",
    "Chuo": "中央",
    "Arakawa": "荒川",
    "Adachi": "足立",
    "Nakano": "中野",
    "Suginami": "杉並",
    "Meguro": "目黒",
    "Kita": "北",
    "Taito": "台東"
  },
  "Kanagawa": {
    "Yokohama": "横浜",
    "Kawasaki": "川崎",
    "Sagamihara": "相模原",
    "Odawara": "小田原",
    "Yokosuka": "横須賀",
    "Fujisawa": "藤沢",
    "Chigasaki": "茅ヶ崎",
    "Zushi": "逗子",
    "Atsugi": "厚木",
    "Kamakura": "鎌倉",
    "Minamiashigara": "南足柄",
    "Hayama": "葉山",
    "Totsuka": "戸塚",
    "Hadano": "秦野",
    "Ebina": "海老名",
    "Isehara": "伊勢原",
    "Miura": "三浦",
    "Sakae": "栄",
    "Tama": "多摩"
  },
  "Niigata": {
    "Niigata": "新潟",
    "Joetsu": "上越",
    "Nagaoka": "長岡",
    "Tsubame": "燕",
    "Sanjo": "三条",
    "Murakami": "村上",
    "Sado": "佐渡",
    "Niitsu": "新津",
    "Agano": "阿賀野",
    "Kamo": "加茂"
  },
  "Toyama": {
    "Toyama": "富山",
    "Takaoka": "高岡",
    "Uozu": "魚津",
    "Fushiki": "伏木",
    "Imizu": "射水",
    "Nanto": "南砺",
    "Tonami": "砺波",
    "Kurobe": "黒部",
    "Shinminato": "新湊",
    "Kamiichi": "上市"
  },
  "Ishikawa": {
    "Kanazawa": "金沢",
    "Wajima": "輪島",
    "Tsubata": "津幡",
    "Nonoichi": "野々市",
    "Suematsu": "末松",
    "Shika": "志賀",
    "Hakusan": "白山",
    "Kaga": "加賀",
    "Takaoka": "高岡",
    "Anamizu": "穴水"
  },
  "Fukui": {
    "Fukui": "福井",
    "Sakai": "坂井",
    "Echizen": "越前",
    "Takahama": "高浜",
    "Ono": "小浜",
    "Katsuyama": "勝山",
    "Obama": "小浜",
    "Sabae": "鯖江",
    "Takefu": "武生",
    "Awano": "粟野"
  },
  "Yamanashi": {
    "Kofu": "甲府",
    "Fujiyoshida": "富士吉田",
    "Minami Alps": "南アルプス",
    "Katsunuma": "勝沼",
    "Tomi": "富士",
    "Yamanashi": "山梨",
    "Fujikawaguchiko": "富士河口湖",
    "Nirasaki": "韮崎",
    "Fujinomiya": "富士宮",
    "Nanbu": "南部"
  },
  "Nagano": {
    "Nagano": "長野",
    "Matsumoto": "松本",
    "Suwa": "諏訪",
    "Shiojiri": "塩尻",
    "Iida": "飯田",
    "Karuizawa": "軽井沢",
    "Ueda": "上田",
    "Okaya": "岡谷",
    "Azumino": "安曇野"
  },
  "Gifu": {
    "Gifu": "岐阜",
    "Takayama": "高山",
    "Ogaki": "大垣",
    "Kakamigahara": "各務原",
    "Ichinomiya": "一宮",
    "Seki": "関",
    "Gero": "下呂",
    "Tarui": "垂井",
    "Toki": "土岐",
    "Minokamo": "美濃加茂"
  },

  "Shizuoka": {
    "Shizuoka": "静岡",
    "Hamamatsu": "浜松",
    "Numazu": "沼津",
    "Fujinomiya": "富士宮",
    "Kakegawa": "掛川",
    "Mishima": "三島",
    "Ito": "伊東",
    "Fujieda": "藤枝",
    "Iwata": "磐田",
    "Toyohashi": "豊橋"
  },
  "Aichi": {
    "Nagoya": "名古屋",
    "Toyota": "豊田",
    "Okazaki": "岡崎",
    "Ichinomiya": "一宮",
    "Nagakute": "長久手",
    "Toyokawa": "豊川",
    "Seto": "瀬戸",
    "Aichi": "愛知",
    "Kariya": "刈谷",
    "Tahara": "田原",
    "Anjo": "安城",
    "Gamou": "蒲郡",
    "Nishio": "西尾",
    "Inazawa": "稲沢",
    "Togo": "東郷",
    "Shinshiro": "新城",
    "Tojo": "東浄",
    "Aisai": "愛西",
    "Mikawa": "三河",
    "Komaki": "小牧"
  },
  "Mie": {
    "Tsu": "津",
    "Ise": "伊勢",
    "Yokkaichi": "四日市",
    "Kameyama": "亀山",
    "Iga": "伊賀",
    "Kashihara": "柏原",
    "Shima": "志摩",
    "Owase": "尾鷲",
    "Kuwana": "桑名",
    "Taki": "多気"
  },
  "Shiga": {
    "Otsu": "大津",
    "Kusatsu": "草津",
    "Hikone": "彦根",
    "Omihachiman": "近江八幡",
    "Koka": "甲賀",
    "Tachikawa": "立川",
    "Minami-Kyoto": "南京",
    "Inuyama": "犬山",
    "Yasu": "八日市",
    "Nagahama": "長浜"
  },
  "Kyoto": {
    "Kyoto": "京都",
    "Uji": "宇治",
    "Kameoka": "亀岡",
    "Maizuru": "舞鶴",
    "Fushimi": "伏見",
    "Nagaokakyo": "長岡京",
    "Kizugawa": "木津川",
    "Kyotanabe": "京田辺",
    "Seika": "精華",
    "Sakyo": "左京",
    "Joyo": "城陽",
    "Wazuka": "和束",
    "Nantan": "南丹",
    "Oyamazaki": "大山崎",
    "Mukaijima": "向島",
    "Ibaraki": "茨木"
  },
  "Osaka": {
    "Osaka": "大阪",
    "Sakai": "堺",
    "Takaishi": "高石",
    "Hirakata": "枚方",
    "Toyonaka": "豊中",
    "Takatsuki": "高槻",
    "Ibaraki": "茨木",
    "Suita": "吹田",
    "Daito": "大東",
    "Suminoe": "住之江",
    "Ikeda": "池田",
    "Amagasaki": "尼崎",
    "Settsu": "摂津",
    "Kadoma": "門真",
    "Kishiwada": "岸和田",
    "Kawachinagano": "河内長野",
    "Osakasayama": "大阪狭山",
    "Minoh": "箕面",
    "Sumoto": "洲本",
    "Tondabayashi": "富田林"
  },
  "Hyogo": {
    "Kobe": "神戸",
    "Himeji": "姫路",
    "Amagasaki": "尼崎",
    "Takarazuka": "宝塚",
    "Nishinomiya": "西宮",
    "Kozu": "小津",
    "Sanda": "三田",
    "Toyooka": "豊岡",
    "Tatsuno": "竜野",
    "Minamiawaji": "南淡路"
  },
  "Nara": {
    "Nara": "奈良",
    "Yamatokoriyama": "大和郡山",
    "Sakurai": "桜井",
    "Tenri": "天理",
    "Kashihara": "橿原",
    "Ikoma": "生駒",
    "Koryo": "高野",
    "Heguri": "平群",
    "Gose": "郡山",
    "Sango": "三郷"
  },

  "Wakayama": {
    "Wakayama": "和歌山",
    "Shingu": "新宮",
    "Kainan": "海南",
    "Tanabe": "田辺",
    "Arida": "有田",
    "Gobo": "御坊",
    "Kihoku": "紀北",
    "Kozagawa": "古座川",
    "Yura": "由良"
  },
  "Tottori": {
    "Tottori": "鳥取",
    "Kurayoshi": "倉吉",
    "Yonago": "米子",
    "Sakaiminato": "境港",
    "Tatsuno": "辰野",
    "Hojyo": "宝城",
    "Koyama": "香山",
    "Bunroku": "文禄",
    "Kamo": "加茂"
  },
  "Shimane": {
    "Matsue": "松江",
    "Izumo": "出雲",
    "Unnan": "雲南",
    "Hamada": "浜田",
    "Oki": "隠岐",
    "Masuda": "益田",
    "Kara": "辛",
    "Mihonoseki": "美保関",
    "Yatsuka": "八束",
    "Taki": "多岐"
  },
  "Okayama": {
    "Okayama": "岡山",
    "Kurashiki": "倉敷",
    "Tamano": "玉野",
    "Sanyo": "山陽",
    "Fukuda": "福田",
    "Kibichuo": "吉備中央",
    "Mimasaka": "美作",
    "Osafune": "長船",
    "Seto": "瀬戸",
    "Bizen": "備前"
  },
  "Hiroshima": {
    "Hiroshima": "広島",
    "Kure": "呉",
    "Fukuyama": "福山",
    "Onomichi": "尾道",
    "Takehara": "竹原",
    "Miyoshi": "三次",
    "Mihara": "三原",
    "Akiota": "安芸太田",
    "Saeki": "佐伯",
    "Hatsukaichi": "廿日市"
  },
  "Yamaguchi": {
    "Yamaguchi": "山口",
    "Shimonoseki": "下関",
    "Ube": "宇部",
    "Shuho": "周防",
    "Iwakuni": "岩国",
    "Hofu": "防府",
    "Yoshiki": "吉敷",
    "Sanyo": "山陽",
    "Tabuse": "田布施",
    "Kudamatsu": "下松"
  },
  "Tokushima": {
    "Tokushima": "徳島",
    "Anan": "阿南",
    "Mugi": "牟岐",
    "Komatsu": "小松",
    "Tatsuno": "竜野",
    "Takamatsu": "高松",
    "Zentsuji": "善通寺",
    "Awa": "阿波",
    "Toba": "鳥羽",
    "Nio": "仁尾"
  },
  "Kagawa": {
    "Takamatsu": "高松",
    "Marugame": "丸亀",
    "Tobe": "多度",
    "Sakaide": "坂出",
    "Kanonji": "観音寺",
    "Mitoyo": "三豊",
    "Sanuki": "讃岐",
    "Tamaoka": "玉岡",
    "Zentsuji": "善通寺",
    "Kotohira": "琴平"
  },
  "Ehime": {
    "Matsuyama": "松山",
    "Imabari": "今治",
    "Niihama": "新居浜",
    "Uwajima": "宇和島",
    "Shikokuchuo": "四国中央",
    "Ozu": "大洲",
    "Saijyo": "西条",
    "Tobe": "砥部",
    "Yawatahama": "八幡浜",
    "Matsuno": "松野"
  },
  "Kochi": {
    "Kochi": "高知",
    "Nankoku": "南国",
    "Ooka": "大岡",
    "Niyodogawa": "仁淀川",
    "Aki": "安芸",
    "Sukumo": "宿毛",
    "Konan": "香南",
    "Mihara": "三原",
    "Tosa": "土佐"
  },
  "Fukuoka": {
    "Fukuoka": "福岡",
    "Kitakyushu": "北九州",
    "Kurume": "久留米",
    "Nagasaki": "長崎",
    "Koga": "古賀",
    "Onojo": "太宰府",
    "Chikuzen": "筑前",
    "Dazaifu": "太宰府",
    "Yame": "八女",
    "Yanagawa": "柳川"
  },
  "Saga": {
    "Saga": "佐賀",
    "Karatsu": "唐津",
    "Imari": "伊万里",
    "Tosu": "鳥栖",
    "Shiroishi": "白石",
    "Kawasaki": "川崎",
    "Kudoyama": "久遠山",
    "Ureshino": "嬉野",
    "Takeo": "武雄"
  },
  "Nagasaki": {
    "Nagasaki": "長崎",
    "Sasebo": "佐世保",
    "Isahaya": "諫早",
    "Taku": "多久",
    "Unzen": "雲仙",
    "Shimabara": "島原",
    "Omura": "大村",
    "Nagayo": "長与",
    "Goto": "五島",
    "Yukawa": "湯川"
  },
  "Kumamoto": {
    "Kumamoto": "熊本",
    "Yatsushiro": "八代",
    "Amakusa": "天草",
    "Kikuchi": "菊池",
    "Arao": "荒尾",
    "Hitoyoshi": "人吉",
    "Uto": "宇土",
    "Takamori": "高森",
    "Kosa": "甲佐",
    "Kamimashiki": "上益城"
  },
  "Oita": {
    "Oita": "大分",
    "Beppu": "別府",
    "Nakatsu": "中津",
    "Usa": "宇佐",
    "Saiki": "佐伯",
    "Hita": "日田",
    "Kokonoe": "九重",
    "Taketa": "竹田",
    "Kunisaki": "国東",
    "Bungotakada": "豊後高田"
  },
  "Miyazaki": {
    "Miyazaki": "宮崎",
    "Nichinan": "日南",
    "Kobayashi": "小林",
    "Nobeoka": "延岡",
    "Saito": "西都市",
    "Kirishima": "霧島",
    "Hyuga": "日向",
    "Mimata": "美郷",
    "Ebino": "えびの",
    "Takanabe": "高鍋"
  },
  "Kagoshima": {
    "Kagoshima": "鹿児島",
    "Kanoya": "鹿屋",
    "Izumi": "出水",
    "Satsumasendai": "薩摩川内",
    "Makurazaki": "枕崎",
    "Koshikijima": "甑島",
    "Kirishima": "霧島",
    "Amami": "奄美",
    "Tarumizu": "垂水"
  },
  "Okinawa": {
    "Naha": "那覇",
    "Okinawa": "沖縄",
    "Nago": "名護",
    "Kadena": "嘉手納",
    "Uruma": "うるま",
    "Itoman": "糸満",
    "Motobu": "本部",
    "Onna": "恩納",
    "Nanjo": "南城",
    "Ginoza": "宜野座"
  }
}